// <auto-generated />
using System;
using LatoCruiser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LatoCruiser.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211024132915_LatoApp")]
    partial class LatoApp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LatoCruiser.Models.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BookEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
